name: Node.js CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main", "dev"]

jobs:
    build:
        name: Backend test
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./quirknotes/backend

        strategy:
            matrix:
                node-version: [20.x]

        steps:
        - uses: actions/checkout@v3

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}

        # Install dependencies
        - run: npm i

        # Create and run database
        - run: mkdir data
        - run: cd data
        - run: mkdir db
        - run: cd ..
        - run: mongod --dbpath=./data/db

        # Run server
        - run: npm start

        # Run tests
        - run: npm test